import { ClientDetails, CurrencyOption } from "./types";
import { formatCalendarDate, getInvoiceNumber } from "./utils";

export const FOOTER_LINKS = [
  {
    title: "Free Tools",
    links: [{ title: "Value Pricing Calculator", url: "#" }],
  },
  {
    title: "Invoice",
    links: [{ title: "Send via email", url: "#" }],
  },
  {
    title: "Legal",
    links: [
      { title: "Terms of Services", url: "#" },
      { title: "Privacy Policy", url: "#" },
    ],
  },
  {
    title: "Company",
    links: [
      { title: "Pricing", url: "#" },
      { title: "Affiliates", url: "#" },
      { title: "Blog", url: "#" },
    ],
  },
];

export const SIGNUP_FORM_FIELDS: {
  fieldName:
    | "name"
    | "address"
    | "phoneNumber"
    | "email"
    | "password"
    | "logo"
    | "password.password"
    | "password.confirmPassword";
  label: string;
  placeholder: string;
  phone: boolean;
  type: "text" | "email" | "password" | "tel" | "file";
}[] = [
  {
    fieldName: "name",
    label: "Company Name",
    placeholder: "Inskpire Corp",
    phone: false,
    type: "text",
  },
  {
    fieldName: "address",
    label: "Address",
    placeholder: "Mile 11, West Hills",
    phone: false,
    type: "text",
  },
  {
    fieldName: "email",
    label: "Email",
    placeholder: "company@email.com",
    phone: false,
    type: "email",
  },
  {
    fieldName: "phoneNumber",
    label: "Phone Number",
    placeholder: "Enter phone number",
    phone: true,
    type: "tel",
  },
  {
    fieldName: "password.password",
    label: "Password",
    placeholder: "~k$M@X7#fL0vE!p!a",
    phone: false,
    type: "text",
  },
  {
    fieldName: "password.confirmPassword",
    label: "Confirm Password",
    placeholder: "~k$M@X7#fL0vE!p!a",
    phone: false,
    type: "text",
  },
];

export const SESSION_EXPIRATION = 60 * 60 * 24 * 7;

export const CLIENT_DETAILS_FIELDS: ClientDetails[] = [
  {
    fieldName: "companyName",
    label: "Company Name",
    placeholder: "e.g. Resolut Corporation",
    isSimpleForm: true,
  },
  {
    fieldName: "companyAddress",
    label: "Company Address",
    placeholder: "e.g. 123 Main Street, Accra",
    isSimpleForm: true,
  },
  {
    fieldName: "companyEmail",
    label: "Company Email",
    placeholder: "e.g. info@resolut.com",
    isSimpleForm: true,
  },
  {
    fieldName: "invoiceNumber",
    label: "Invoice Number",
    placeholder: "e.g. INV-2025-001",
    isSimpleForm: true,
  },
  {
    fieldName: "purchaseOrder",
    label: "Purchase Order",
    placeholder: "e.g. PO-789456",
    isSimpleForm: true,
  },
];

export const CONTACT_PERSON_TITLES = [
  { value: "Mr" },
  { value: "Mrs" },
  { value: "Ms" },
  { value: "Other" },
];

export const CURRENCIES: CurrencyOption[] = [
  { value: "د.إ", label: "United Arab Emirates Dirham (AED)" },
  { value: "؋", label: "Afghan Afghani (AFN)" },
  { value: "L", label: "Albanian Lek (ALL)" },
  { value: "֏", label: "Armenian Dram (AMD)" },
  { value: "ƒ-ANG", label: "Netherlands Antillean Guilder (ANG)" },
  { value: "Kz", label: "Angolan Kwanza (AOA)" },
  { value: "ARS", label: "Argentine Peso (ARS)" },
  { value: "A$", label: "Australian Dollar (AUD)" },
  { value: "ƒ-AWG", label: "Aruban Florin (AWG)" },
  { value: "₼", label: "Azerbaijani Manat (AZN)" },
  { value: "KM", label: "Bosnia-Herzegovina Convertible Mark (BAM)" },
  { value: "$-BBD", label: "Barbadian Dollar (BBD)" },
  { value: "৳", label: "Bangladeshi Taka (BDT)" },
  { value: "лв", label: "Bulgarian Lev (BGN)" },
  { value: ".د.ب", label: "Bahraini Dinar (BHD)" },
  { value: "FBu", label: "Burundian Franc (BIF)" },
  { value: "BMD", label: "Bermudan Dollar (BMD)" },
  { value: "BND", label: "Brunei Dollar (BND)" },
  { value: "Bs.", label: "Bolivian Boliviano (BOB)" },
  { value: "R$", label: "Brazilian Real (BRL)" },
  { value: "BSD", label: "Bahamian Dollar (BSD)" },
  { value: "Nu.", label: "Bhutanese Ngultrum (BTN)" },
  { value: "BWP", label: "Botswanan Pula (BWP)" },
  { value: "BYN", label: "Belarusian Ruble (BYN)" },
  { value: "BZ$", label: "Belize Dollar (BZD)" },
  { value: "C$-CAD", label: "Canadian Dollar (CAD)" },
  { value: "CDF", label: "Congolese Franc (CDF)" },
  { value: "CHF", label: "Swiss Franc (CHF)" },
  { value: "CLP", label: "Chilean Peso (CLP)" },
  { value: "¥-CNY", label: "Chinese Yuan (CNY)" },
  { value: "COP", label: "Colombian Peso (COP)" },
  { value: "₡", label: "Costa Rican Colón (CRC)" },
  { value: "₱-CUP", label: "Cuban Peso (CUP)" },
  { value: "CVE", label: "Cape Verdean Escudo (CVE)" },
  { value: "Kč", label: "Czech Koruna (CZK)" },
  { value: "Fdj", label: "Djiboutian Franc (DJF)" },
  { value: "DKK", label: "Danish Krone (DKK)" },
  { value: "RD$", label: "Dominican Peso (DOP)" },
  { value: "د.ج", label: "Algerian Dinar (DZD)" },
  { value: "EGP", label: "Egyptian Pound (EGP)" },
  { value: "Nfk", label: "Eritrean Nakfa (ERN)" },
  { value: "ETB", label: "Ethiopian Birr (ETB)" },
  { value: "€", label: "Euro (EUR)" },
  { value: "FJD", label: "Fijian Dollar (FJD)" },
  { value: "FKP", label: "Falkland Islands Pound (FKP)" },
  { value: "£-GBP", label: "British Pound (GBP)" },
  { value: "₾", label: "Georgian Lari (GEL)" },
  { value: "GGP", label: "Guernsey Pound (GGP)" },
  { value: "₵", label: "Ghanaian Cedi (GHS)" },
  { value: "GIP", label: "Gibraltar Pound (GIP)" },
  { value: "GMD", label: "Gambian Dalasi (GMD)" },
  { value: "GNF", label: "Guinean Franc (GNF)" },
  { value: "GTQ", label: "Guatemalan Quetzal (GTQ)" },
  { value: "GYD", label: "Guyanaese Dollar (GYD)" },
  { value: "HK$", label: "Hong Kong Dollar (HKD)" },
  { value: "HNL", label: "Honduran Lempira (HNL)" },
  { value: "HUF", label: "Hungarian Forint (HUF)" },
  { value: "IDR", label: "Indonesian Rupiah (IDR)" },
  { value: "₪", label: "Israeli New Shekel (ILS)" },
  { value: "IMP", label: "Manx Pound (IMP)" },
  { value: "₹", label: "Indian Rupee (INR)" },
  { value: "ع.د", label: "Iraqi Dinar (IQD)" },
  { value: "﷼-IRR", label: "Iranian Rial (IRR)" },
  { value: "ISK", label: "Icelandic Króna (ISK)" },
  { value: "JEP", label: "Jersey Pound (JEP)" },
  { value: "J$", label: "Jamaican Dollar (JMD)" },
  { value: "JD", label: "Jordanian Dinar (JOD)" },
  { value: "¥-JPY", label: "Japanese Yen (JPY)" },
  { value: "KSh", label: "Kenyan Shilling (KES)" },
  { value: "сом", label: "Kyrgystani Som (KGS)" },
  { value: "៛", label: "Cambodian Riel (KHR)" },
  { value: "CF", label: "Comorian Franc (KMF)" },
  { value: "KPW", label: "North Korean Won (KPW)" },
  { value: "₩", label: "South Korean Won (KRW)" },
  { value: "K.D.", label: "Kuwaiti Dinar (KWD)" },
  { value: "KYD", label: "Cayman Islands Dollar (KYD)" },
  { value: "₸", label: "Kazakhstani Tenge (KZT)" },
  { value: "₭", label: "Laotian Kip (LAK)" },
  { value: "LBP", label: "Lebanese Pound (LBP)" },
  { value: "₨-LKR", label: "Sri Lankan Rupee (LKR)" },
  { value: "LRD", label: "Liberian Dollar (LRD)" },
  { value: "LSL", label: "Lesotho Loti (LSL)" },
  { value: "ل.د", label: "Libyan Dinar (LYD)" },
  { value: "د.م.", label: "Moroccan Dirham (MAD)" },
  { value: "MDL", label: "Moldovan Leu (MDL)" },
  { value: "Ar", label: "Malagasy Ariary (MGA)" },
  { value: "ден", label: "Macedonian Denar (MKD)" },
  { value: "MMK", label: "Myanma Kyat (MMK)" },
  { value: "₮", label: "Mongolian Tugrik (MNT)" },
  { value: "MOP$", label: "Macanese Pataca (MOP)" },
  { value: "UM", label: "Mauritanian Ouguiya (MRU)" },
  { value: "₨-MUR", label: "Mauritian Rupee (MUR)" },
  { value: ".ރ", label: "Maldivian Rufiyaa (MVR)" },
  { value: "MK", label: "Malawian Kwacha (MWK)" },
  { value: "MXN", label: "Mexican Peso (MXN)" },
  { value: "RM", label: "Malaysian Ringgit (MYR)" },
  { value: "MT", label: "Mozambican Metical (MZN)" },
  { value: "NAD", label: "Namibian Dollar (NAD)" },
  { value: "₦", label: "Nigerian Naira (NGN)" },
  { value: "C$-NIO", label: "Nicaraguan Córdoba (NIO)" },
  { value: "NOK", label: "Norwegian Krone (NOK)" },
  { value: "₨-NPR", label: "Nepalese Rupee (NPR)" },
  { value: "NZ$", label: "New Zealand Dollar (NZD)" },
  { value: "﷼-OMR", label: "Omani Rial (OMR)" },
  { value: "B/.", label: "Panamanian Balboa (PAB)" },
  { value: "S/", label: "Peruvian Sol (PEN)" },
  { value: "PGK", label: "Papua New Guinean Kina (PGK)" },
  { value: "₱-PHP", label: "Philippine Peso (PHP)" },
  { value: "₨-PKR", label: "Pakistani Rupee (PKR)" },
  { value: "zł", label: "Polish Zloty (PLN)" },
  { value: "₲", label: "Paraguayan Guarani (PYG)" },
  { value: "﷼-QAR", label: "Qatari Rial (QAR)" },
  { value: "lei", label: "Romanian Leu (RON)" },
  { value: "дин.", label: "Serbian Dinar (RSD)" },
  { value: "₽", label: "Russian Ruble (RUB)" },
  { value: "R₣", label: "Rwandan Franc (RWF)" },
  { value: "﷼-SAR", label: "Saudi Riyal (SAR)" },
  { value: "$-SBD", label: "Solomon Islands Dollar (SBD)" },
  { value: "₨-SCR", label: "Seychellois Rupee (SCR)" },
  { value: "ج.س.", label: "Sudanese Pound (SDG)" },
  { value: "SEK", label: "Swedish Krona (SEK)" },
  { value: "S$", label: "Singapore Dollar (SGD)" },
  { value: "SHP", label: "Saint Helena Pound (SHP)" },
  { value: "SLL", label: "Sierra Leonean Leone (SLL)" },
  { value: "SOS", label: "Somali Shilling (SOS)" },
  { value: "SRD", label: "Surinamese Dollar (SRD)" },
  { value: "SSP", label: "South Sudanese Pound (SSP)" },
  { value: "STN", label: "São Tomé and Príncipe Dobra (STN)" },
  { value: "£S", label: "Syrian Pound (SYP)" },
  { value: "SZL", label: "Swazi Lilangeni (SZL)" },
  { value: "฿", label: "Thai Baht (THB)" },
  { value: "TJS", label: "Tajikistani Somoni (TJS)" },
  { value: "TMT", label: "Turkmenistani Manat (TMT)" },
  { value: "د.ت", label: "Tunisian Dinar (TND)" },
  { value: "T$", label: "Tongan Paʻanga (TOP)" },
  { value: "₺", label: "Turkish Lira (TRY)" },
  { value: "TT$", label: "Trinidad and Tobago Dollar (TTD)" },
  { value: "NT$", label: "New Taiwan Dollar (TWD)" },
  { value: "TSh", label: "Tanzanian Shilling (TZS)" },
  { value: "₴", label: "Ukrainian Hryvnia (UAH)" },
  { value: "USh", label: "Ugandan Shilling (UGX)" },
  { value: "$-USD", label: "United States Dollar (USD)" },
  { value: "$U", label: "Uruguayan Peso (UYU)" },
  { value: "UZS", label: "Uzbekistan Som (UZS)" },
  { value: "VES", label: "Venezuelan Bolívar Soberano (VES)" },
  { value: "₫", label: "Vietnamese Dong (VND)" },
  { value: "VUV", label: "Vanuatu Vatu (VUV)" },
  { value: "WST", label: "Samoan Tālā (WST)" },
  { value: "FCFA", label: "Central African CFA Franc (XAF)" },
  { value: "XCD", label: "East Caribbean Dollar (XCD)" },
  { value: "CFA", label: "West African CFA Franc (XOF)" },
  { value: "₣", label: "CFP Franc (XPF)" },
  { value: "﷼-YER", label: "Yemeni Rial (YER)" },
  { value: "ZAR", label: "South African Rand (ZAR)" },
  { value: "ZK", label: "Zambian Kwacha (ZMW)" },
  { value: "Z$", label: "Zimbabwean Dollar (ZWL)" },
];

export const NOTES_TERMS = [
  { name: "notes", label: "Notes", placeholder: "e.g. notes for client" },
  { name: "terms", label: "Terms", placeholder: "e.g. terms of service" },
];

export const INVOICE_FORM_DEFAULTS = {
  companyName: "",
  companyAddress: "",
  companyEmail: "",
  contactPerson: {
    title: "Mr",
    name: "",
  },
  phoneNumber: "",
  purchaseOrder: getInvoiceNumber(),
  invoiceNumber: getInvoiceNumber(),
  invoiceDate: formatCalendarDate(new Date()),
  dueDate: formatCalendarDate(new Date()),

  customInvoiceFields: [],

  invoiceItems: [
    {
      item: "",
      quantity: "1",
      unitPrice: {
        currency: "₵",
        price: "0.00",
      },
      subTotal: "0.00",
      description: "",
    },
  ],

  notes: "",
  terms: "",
  logo: undefined,

  discount: "",
  tax: "",
  shipping: "",
};
